name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  terraform-python-test:
    name: Python test for lambdas
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ${{github.workspace}}/terraform/src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ${{github.workspace}}/terraform/src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true

    - name: Test with pytest
      env:
        gmail_mail: "awss.unipv@gmail.com"
        psw_gmail: ${{ secrets.GMAIL_PASSWORD }}
      run: |
        pytest test_sendMail.py
      working-directory: ${{github.workspace}}/.github/workflows/tests/

  docker-python-test:
    name: Test Python orchestrator
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r ${{github.workspace}}/.github/workflows/requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ${{github.workspace}}/docker/src/run.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ${{github.workspace}}/docker/src/run.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true

    - name: Test with pytest
      run: |
        pytest test_run.py
      working-directory: ${{github.workspace}}/.github/workflows/tests/

  c-test:
    name: Build and test C code
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      working-directory: ${{github.workspace}}/docker/src/
      run: |
        make

    - name: Test
      working-directory: ${{github.workspace}}/.github/workflows/tests/
      run: |
        cp ${{github.workspace}}/docker/src/lcs .
        if [[ $(./c-test.sh) ]]; then exit 1; else echo "Test passed"; fi
      
    - name: Upload lcs artifact
      uses: actions/upload-artifact@v3
      with:
        name: lcs
        path: ${{github.workspace}}/docker/src/lcs

  docker-container:
    name: Build Docker container
    runs-on: ubuntu-latest
    needs: [c-test,docker-python-test]
    environment: Production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Download lcs artifact
      uses: actions/download-artifact@v3
      with:
        name: lcs
        path: ${{github.workspace}}/docker/src/

    - name: Build Docker image
      id: build-image
      run: |
        docker build -t lcs-container .
        docker save lcs-container > /tmp/lcs-container.tar
      working-directory: ${{github.workspace}}/docker/

    - name: Upload image artifact
      uses: actions/upload-artifact@v3
      with:
        name: lcs-container
        path: /tmp/lcs-container.tar


  terraform:
    name: 'Build Terraform infrastructure'
    needs: terraform-python-test
    runs-on: ubuntu-latest
    environment: Production

    outputs:
      output-region: ${{ steps.apply.outputs.region }}
      output-ecr-repo: ${{ steps.apply.outputs.repository }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: terraform
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      id: setup
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: format
      run: terraform fmt -check
      continue-on-error: true

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan

      # On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        terraform apply -auto-approve
        echo "::set-output name=region::$(terraform output -raw region)"
        echo "::set-output name=repository::$(terraform output -raw ecs-repo)"


  deploy-ecs:
    name: Deploy image on ECS
    needs: [terraform, docker-container]
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ needs.terraform.outputs.output-region}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Download image artifact
      uses: actions/download-artifact@v3
      with:
        name: lcs-container
        path: /tmp

    - name: Load Docker image
      run: |
        docker load --input /tmp/lcs-container.tar

    - name: Push image to Amazon ECR
      id: push-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker tag lcs-container ${ECR_REGISTRY}/${{needs.terraform.outputs.output-ecr-repo}}:latest
        docker push ${ECR_REGISTRY}/${{needs.terraform.outputs.output-ecr-repo}}:latest
        echo "::set-output name=image::${ECR_REGISTRY}/${{needs.terraform.outputs.output-ecr-repo}}:latest"